version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: razvan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatroom
    networks:
      - chatroom-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U razvan -d chatroom"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - chatroom-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  chatroom:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - chatroom-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

networks:
  chatroom-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local